
export const CLOUD = "yoav-cloud";

export const VIEW_STATES = {
	EXPANDED: "EXPANDED",
	MINIFIED: "MINIFIED",
};

export const FETCH_STATUSES = {
	NONE: "NONE",
	PROGRESS: "PROGRESS",
	FAILED: "FAILED",
};

export const TYPES = {
	SET_PHOTOS: "SET_PHOTOS",

	SET_SELECTED_PHOTO: "SET_SELECTED_PHOTO",

	TOGGLE_VIEW_STATE: "TOGGLE_VIEW_STATE",

	SET_FETCH_STATUS: "SET_FETCH_STATUS",

	FETCH_PHOTOS: "FETCH_PHOTOS",

	SET_EXPOSED_PHOTO: "SET_EXPOSED_PHOTO",
};